# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRIxXKhXndzwdewffFAz9Jnsk1C0CI0Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/nepsealpha_export_price_NABIL_2013-01-26_2023-01-26.csv')

df.sample(10)

print(df.shape)
print(df.duplicated().sum())

df.info()

df.describe().transpose()

df_details_tbl = pd.DataFrame({
    'Unique':df.nunique(),
    'data_type':df.dtypes.values,
    'Null':df.isna().sum(), 
    'null_percent':df.isna().sum()/len(df)
})

df_details_tbl

numerical_dtypes = df.select_dtypes(exclude='O')
categorical_dtypes = df.select_dtypes(include='O')

numerical_dtypes.sample(5)

categorical_dtypes.sample(5)

"""# **Visualizations**

"""

sns.set_style('darkgrid')
colors = ['#ED72A3','#8565F0','#22559C', '#F27370','#FA9856','#EDE862']

# heatmaps
'''
    The correlation is only possible to numerical values.
'''
sns.heatmap(df.corr(), annot=True, fmt='.2f')

# visualizations on the mean of open, high, low, close and volume with year, month and day.

df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month

# grouped_df = df.groupby('Year',as_index=False).agg({'Open':'mean'})
# grouped_df



sns.barplot(data=df, x='Year', y='Volume')

sns.lineplot(data=df, x='Year', y='Volume', palette=colors, ci=None)

sns.lineplot(data=df, x='Year', y='Close', ci=None)

plt.figure(figsize=(15,7))
plt.plot(df['Date'], df['Volume'])
plt.show()

